[build]
  # Build command
  command = "npm run build"
  
  # Output directory
  publish = "out"

[build.environment]
  # Environment variables for build
  NODE_VERSION = "20"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

# SPA routing configuration
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Caching configuration
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()" 